"""phase1_schema

Revision ID: 20260924_0002
Revises: 20260923_0001
Create Date: 2026-09-24 11:32:36.163167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260924_0002'
down_revision: Union[str, Sequence[str], None] = '20260923_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('r2_bucket', sa.Text(), nullable=True),
    sa.Column('r2_key', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("doc_type IN ('resume', 'jd')", name='ck_documents_doc_type'),
    sa.CheckConstraint("parse_status IN ('pending', 'processing', 'ready', 'failed')", name='ck_documents_parse_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_user_id', 'documents', ['user_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('claim_type', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('measurability', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('source_chunk_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'"), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claims_document_id', 'claims', ['document_id'], unique=False)
    op.create_table('document_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_sections_document_id', 'document_sections', ['document_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resume_document_id', sa.UUID(), nullable=True),
    sa.Column('jd_document_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'preparing'"), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('n_target', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lexicon', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('preparing', 'ready', 'live', 'completed', 'failed')", name='ck_interview_sessions_status'),
    sa.ForeignKeyConstraint(['jd_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interview_sessions_status', 'interview_sessions', ['status'], unique=False)
    op.create_index('ix_interview_sessions_user_id', 'interview_sessions', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('parent_chunk_id', sa.UUID(), nullable=True),
    sa.Column('chunk_kind', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(384), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_section_id', 'document_chunks', ['section_id'], unique=False)
    op.create_table('session_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_markdown', sa.Text(), nullable=True),
    sa.Column('r2_pdf_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'ready', 'failed')", name='ck_session_reports_status'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_session_reports_session_id')
    )
    op.create_table('session_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('hire_signal', sa.Text(), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('coverage_summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("hire_signal IN ('needs_work', 'mixed', 'solid', 'strong')", name='ck_session_results_hire_signal'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_session_results_session_id')
    )
    op.create_table('session_topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'planned'"), nullable=False),
    sa.Column('soft_cap_seconds', sa.Integer(), server_default=sa.text('210'), nullable=False),
    sa.Column('hard_cap_seconds', sa.Integer(), server_default=sa.text('330'), nullable=False),
    sa.Column('seconds_spent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rollup_scores', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'active', 'scored', 'skipped')", name='ck_session_topics_status'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_topics_session_id_status', 'session_topics', ['session_id', 'status'], unique=False)
    op.create_table('frontier_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'locked'"), nullable=False),
    sa.Column('prereqs', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('question_mode', sa.Text(), server_default=sa.text("'parallel'"), nullable=False),
    sa.Column('max_followups', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('followups_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('depth_level', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("question_mode IN ('parallel', 'direct', 'escalate')", name='ck_frontier_nodes_question_mode'),
    sa.CheckConstraint("status IN ('locked', 'available', 'in_progress', 'exhausted', 'abandoned')", name='ck_frontier_nodes_status'),
    sa.ForeignKeyConstraint(['parent_id'], ['frontier_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['session_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_frontier_nodes_session_id_status', 'frontier_nodes', ['session_id', 'status'], unique=False)
    op.create_index('ix_frontier_nodes_topic_id', 'frontier_nodes', ['topic_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('frontier_node_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('corrections', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('agent', 'user')", name='ck_turns_role'),
    sa.ForeignKeyConstraint(['frontier_node_id'], ['frontier_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['session_topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_turns_session_id_created_at', 'turns', ['session_id', 'created_at'], unique=False)
    op.create_table('turn_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('correctness', sa.SmallInteger(), nullable=False),
    sa.Column('relevance', sa.SmallInteger(), nullable=False),
    sa.Column('depth', sa.SmallInteger(), nullable=False),
    sa.Column('structure', sa.SmallInteger(), nullable=False),
    sa.Column('honesty', sa.SmallInteger(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint('correctness BETWEEN 0 AND 5', name='ck_turn_scores_correctness'),
    sa.CheckConstraint('depth BETWEEN 0 AND 5', name='ck_turn_scores_depth'),
    sa.CheckConstraint('honesty BETWEEN 0 AND 5', name='ck_turn_scores_honesty'),
    sa.CheckConstraint('relevance BETWEEN 0 AND 5', name='ck_turn_scores_relevance'),
    sa.CheckConstraint('structure BETWEEN 0 AND 5', name='ck_turn_scores_structure'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id', name='uq_turn_scores_turn_id')
    )
    op.create_table('turn_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('turn_score_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_score_id'], ['turn_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_turn_evidence_turn_score_id', 'turn_evidence', ['turn_score_id'], unique=False)
    op.execute(
        "CREATE INDEX ix_document_chunks_embedding_hnsw "
        "ON document_chunks USING hnsw (embedding vector_cosine_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_turn_evidence_turn_score_id', table_name='turn_evidence')
    op.drop_table('turn_evidence')
    op.drop_table('turn_scores')
    op.drop_index('ix_turns_session_id_created_at', table_name='turns')
    op.drop_table('turns')
    op.drop_index('ix_frontier_nodes_topic_id', table_name='frontier_nodes')
    op.drop_index('ix_frontier_nodes_session_id_status', table_name='frontier_nodes')
    op.drop_table('frontier_nodes')
    op.drop_index('ix_session_topics_session_id_status', table_name='session_topics')
    op.drop_table('session_topics')
    op.drop_table('session_results')
    op.drop_table('session_reports')
    op.execute('DROP INDEX IF EXISTS ix_document_chunks_embedding_hnsw')
    op.drop_index('ix_document_chunks_section_id', table_name='document_chunks')
    op.drop_index('ix_document_chunks_document_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_interview_sessions_user_id', table_name='interview_sessions')
    op.drop_index('ix_interview_sessions_status', table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index('ix_document_sections_document_id', table_name='document_sections')
    op.drop_table('document_sections')
    op.drop_index('ix_claims_document_id', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_documents_user_id', table_name='documents')
    op.drop_table('documents')
    op.drop_table('users')
    # ### end Alembic commands ###
